//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessDay
    {
        public BusinessDay()
        {
            this.Deposits = new HashSet<Deposit>();
            this.Shifts = new HashSet<Shift>();
        }
    
        public System.Guid Id { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<System.DateTime> CheckoutDateStamp { get; set; }
        public System.DateTime BusinessDayDateStamp { get; set; }
        public System.Guid CloseoutTerminalId { get; set; }
        public Nullable<System.Guid> BatchSummaryId { get; set; }
        public Nullable<System.Guid> BatchCloseId { get; set; }
        public string AmNotes { get; set; }
        public Nullable<int> WeatherType { get; set; }
        public string LunchNotes { get; set; }
        public string PmNotes { get; set; }
        public Nullable<System.Guid> StoreLocationId { get; set; }
        public Nullable<System.Guid> ExtendedBoolTableId { get; set; }
        public Nullable<System.Guid> ExtendedStringTableId { get; set; }
        public Nullable<System.Guid> ExtendedDecimalTableId { get; set; }
        public Nullable<System.Guid> ExtendedIntTableId { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable1Id { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable2Id { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
        public bool WasSyncedWithReportingService { get; set; }
    
        public virtual StoreLocation StoreLocation { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
