//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public System.Guid Id { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
        public decimal AmountPaid { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid OrderId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
