//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionModifier
    {
        public ExceptionModifier()
        {
            this.ExceptionModifierGroups = new HashSet<ExceptionModifierGroup>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ForcedModGroupOnExceptionModId { get; set; }
        public Nullable<System.Guid> ExtendedBoolTableId { get; set; }
        public Nullable<System.Guid> ExtendedStringTableId { get; set; }
        public Nullable<System.Guid> ExtendedDecimalTableId { get; set; }
        public Nullable<System.Guid> ExtendedIntTableId { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable1Id { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable2Id { get; set; }
        public string Color { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public byte[] Image { get; set; }
        public string Name { get; set; }
        public int PriceMethod { get; set; }
        public bool PromptForPrice { get; set; }
        public bool IsGiftCard { get; set; }
        public decimal PricePerUnitOfWeight { get; set; }
        public bool IsAgeRestrict { get; set; }
        public bool IsDisplayOnBilling { get; set; }
        public bool UseWeightPricing { get; set; }
        public decimal UnitOfWeightSize { get; set; }
        public bool CountsAsSalesRevenue { get; set; }
        public decimal Price { get; set; }
        public bool RemoveAtZeroCount { get; set; }
        public long Downtick { get; set; }
        public Nullable<int> MaxFloorQty { get; set; }
        public int MenuPosition { get; set; }
        public string Sku { get; set; }
        public string Plu { get; set; }
        public string Upc { get; set; }
        public string LongName { get; set; }
        public int CalorieCount { get; set; }
        public Nullable<System.Guid> RecipeId { get; set; }
        public System.Guid RevenueTypeId { get; set; }
        public Nullable<System.Guid> OrderedRecipeId { get; set; }
        public Nullable<System.Guid> SurchargeGroupId { get; set; }
        public Nullable<System.Guid> TaxGroupId { get; set; }
        public Nullable<System.Guid> ProductGroupPrinterId { get; set; }
        public Nullable<System.Guid> InclusiveTipRateId { get; set; }
    
        public virtual ICollection<ExceptionModifierGroup> ExceptionModifierGroups { get; set; }
    }
}
