//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedBoolTable
    {
        public System.Guid Id { get; set; }
        public bool F1 { get; set; }
        public bool F2 { get; set; }
        public bool F3 { get; set; }
        public bool F4 { get; set; }
        public bool F5 { get; set; }
        public bool F6 { get; set; }
        public bool F7 { get; set; }
        public bool F8 { get; set; }
        public bool F9 { get; set; }
        public bool F10 { get; set; }
        public bool F11 { get; set; }
        public bool F12 { get; set; }
        public bool F13 { get; set; }
        public bool F14 { get; set; }
        public bool F15 { get; set; }
        public bool F16 { get; set; }
        public bool F17 { get; set; }
        public bool F18 { get; set; }
        public bool F19 { get; set; }
        public bool F20 { get; set; }
        public bool F21 { get; set; }
        public bool F22 { get; set; }
        public bool F23 { get; set; }
        public bool F24 { get; set; }
        public bool F25 { get; set; }
        public bool F26 { get; set; }
        public bool F27 { get; set; }
        public bool F28 { get; set; }
        public bool F29 { get; set; }
        public bool F30 { get; set; }
        public bool F31 { get; set; }
        public bool F32 { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
    }
}
