//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedDecimalTable
    {
        public System.Guid Id { get; set; }
        public decimal F1 { get; set; }
        public decimal F2 { get; set; }
        public decimal F3 { get; set; }
        public decimal F4 { get; set; }
        public decimal F5 { get; set; }
        public decimal F6 { get; set; }
        public decimal F7 { get; set; }
        public decimal F8 { get; set; }
        public decimal F9 { get; set; }
        public decimal F10 { get; set; }
        public decimal F11 { get; set; }
        public decimal F12 { get; set; }
        public decimal F13 { get; set; }
        public decimal F14 { get; set; }
        public decimal F15 { get; set; }
        public decimal F16 { get; set; }
        public decimal F17 { get; set; }
        public decimal F18 { get; set; }
        public decimal F19 { get; set; }
        public decimal F20 { get; set; }
        public decimal F21 { get; set; }
        public decimal F22 { get; set; }
        public decimal F23 { get; set; }
        public decimal F24 { get; set; }
        public decimal F25 { get; set; }
        public decimal F26 { get; set; }
        public decimal F27 { get; set; }
        public decimal F28 { get; set; }
        public decimal F29 { get; set; }
        public decimal F30 { get; set; }
        public decimal F31 { get; set; }
        public decimal F32 { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
    }
}
