//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedLinkTable
    {
        public System.Guid Id { get; set; }
        public bool IsAccessLevelLink { get; set; }
        public bool IsAutoGratuityLink { get; set; }
        public bool IsAutoGratuityCloneLink { get; set; }
        public bool IsBreaklLink { get; set; }
        public bool IsBusinessDayLink { get; set; }
        public bool IsDayPartLink { get; set; }
        public bool IsDepositLink { get; set; }
        public bool IsDiscountLink { get; set; }
        public bool IsDiscountCloneLink { get; set; }
        public bool IsExceptionModifierLink { get; set; }
        public bool IsExceptionModifierGroupLink { get; set; }
        public bool IsFingerPasswordLink { get; set; }
        public bool IsForcedModifierLink { get; set; }
        public bool IsForcedModifierGroupLink { get; set; }
        public bool IsGiftCardsSoldLink { get; set; }
        public bool IsGlCodeLink { get; set; }
        public bool IsHouseAccountLink { get; set; }
        public bool IsInclusiveTipRateLink { get; set; }
        public bool IsInventoryLogCountLink { get; set; }
        public bool IsInvoiceLineItemLink { get; set; }
        public bool IsJobCodeLink { get; set; }
        public bool IsLayoutObjLink { get; set; }
        public bool IsLocationLayoutLink { get; set; }
        public bool IsMenuLink { get; set; }
        public bool IsMenuGroupLink { get; set; }
        public bool IsNoSaleLink { get; set; }
        public bool IsOrderLink { get; set; }
        public bool IsOrderedRecipeLink { get; set; }
        public bool IsPageLayoutStructureLink { get; set; }
        public bool IsPaygradeLink { get; set; }
        public bool IsPaymentLink { get; set; }
        public bool IsPaymentReasonLink { get; set; }
        public bool IsPayrollRunLink { get; set; }
        public bool IsPciLogLink { get; set; }
        public bool IsPriceIntervalDiscountLink { get; set; }
        public bool IsPrinterLink { get; set; }
        public bool IsPrinterExclusionLink { get; set; }
        public bool IsPrinterGroupLink { get; set; }
        public bool IsProcessorConfigurationLink { get; set; }
        public bool IsProductLink { get; set; }
        public bool IsProductGroupLink { get; set; }
        public bool IsProfitCenterLink { get; set; }
        public bool IsReceipeLink { get; set; }
        public bool IsRecipeIngredientLink { get; set; }
        public bool IsReceipeProductLink { get; set; }
        public bool IsRevenueTypeLink { get; set; }
        public bool IsRoleLink { get; set; }
        public bool IsSaleLink { get; set; }
        public bool IsScheduleLink { get; set; }
        public bool IsShiftLink { get; set; }
        public bool IsSmsConfigurationLink { get; set; }
        public bool IsSpecialPayLink { get; set; }
        public bool IsStoreLocationLink { get; set; }
        public bool IsSurchargeAccountLink { get; set; }
        public bool IsSysConfigLink { get; set; }
        public bool IsTaxConfigurationLink { get; set; }
        public bool IsTaxConfigurationCloneLink { get; set; }
        public bool IsTaxGroupLink { get; set; }
        public bool IsTenderTypeLink { get; set; }
        public bool IsTerminalLink { get; set; }
        public bool IsTerminalPrinterMapLink { get; set; }
        public bool IsTimePunchLink { get; set; }
        public bool IsTransactionLink { get; set; }
        public bool IsUserLink { get; set; }
        public bool IsVendorAccountLink { get; set; }
        public bool IsWorkCenterLink { get; set; }
        public bool BoolPayload { get; set; }
        public string StringPayload { get; set; }
        public decimal DecimalPayload { get; set; }
        public int IntPayload { get; set; }
        public System.Guid Fk1 { get; set; }
        public System.Guid Fk2 { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
    }
}
