//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedIntTable
    {
        public System.Guid Id { get; set; }
        public int F1 { get; set; }
        public int F2 { get; set; }
        public int F3 { get; set; }
        public int F4 { get; set; }
        public int F5 { get; set; }
        public int F6 { get; set; }
        public int F7 { get; set; }
        public int F8 { get; set; }
        public int F9 { get; set; }
        public int F10 { get; set; }
        public int F11 { get; set; }
        public int F12 { get; set; }
        public int F13 { get; set; }
        public int F14 { get; set; }
        public int F15 { get; set; }
        public int F16 { get; set; }
        public int F17 { get; set; }
        public int F18 { get; set; }
        public int F19 { get; set; }
        public int F20 { get; set; }
        public int F21 { get; set; }
        public int F22 { get; set; }
        public int F23 { get; set; }
        public int F24 { get; set; }
        public int F25 { get; set; }
        public int F26 { get; set; }
        public int F27 { get; set; }
        public int F28 { get; set; }
        public int F29 { get; set; }
        public int F30 { get; set; }
        public int F31 { get; set; }
        public int F32 { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
    }
}
