//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayoutObj
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExtendedBoolTableId { get; set; }
        public Nullable<System.Guid> ExtendedStringTableId { get; set; }
        public Nullable<System.Guid> ExtendedDecimalTableId { get; set; }
        public Nullable<System.Guid> ExtendedIntTableId { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable1Id { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable2Id { get; set; }
        public decimal Height { get; set; }
        public decimal Width { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public string Image { get; set; }
        public string Foreground { get; set; }
        public string BackgroundStart { get; set; }
        public string BackgroundEnd { get; set; }
        public int FunctionNumber { get; set; }
        public string SpareString { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public string Style { get; set; }
        public string Tag { get; set; }
        public Nullable<int> PagedId { get; set; }
        public string ButtonText { get; set; }
        public string FontColorStr { get; set; }
        public string BorderColorStr { get; set; }
        public string BackgroundColorStr { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
    }
}
