//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnePosStore
    {
        public long ID { get; set; }
        public string StoreName { get; set; }
        public string StoreOwnerName { get; set; }
        public string StoreUniqueKey { get; set; }
        public string StoreAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string LicenseExpiry { get; set; }
        public string AdminUsername { get; set; }
        public string AdminPassword { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StoreStatus { get; set; }
    
        public virtual OnePosStoreStatu OnePosStoreStatu { get; set; }
    }
}
