//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExtendedBoolTableId { get; set; }
        public Nullable<System.Guid> ExtendedStringTableId { get; set; }
        public Nullable<System.Guid> ExtendedDecimalTableId { get; set; }
        public Nullable<System.Guid> ExtendedIntTableId { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable1Id { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable2Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Details { get; set; }
        public bool AffectsCash { get; set; }
        public decimal Amount { get; set; }
        public bool WasChangeFromVoucher { get; set; }
        public bool WasChangeFromGiftCard { get; set; }
        public bool WasCreditCardAdvance { get; set; }
        public int TransactionType { get; set; }
        public bool WasDrawerStart { get; set; }
        public bool WasDrawerEnd { get; set; }
        public bool WasPaidIn { get; set; }
        public System.Guid DaypartId { get; set; }
        public System.Guid RevenueCenterId { get; set; }
        public Nullable<System.Guid> TransactionTypeId { get; set; }
        public System.Guid ReasonId { get; set; }
        public Nullable<System.Guid> TerminalId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public System.Guid ShiftId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> TenderType_Id { get; set; }
    
        public virtual Shift Shift { get; set; }
        public virtual TenderType TenderType { get; set; }
    }
}
