//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceIntervalDiscount
    {
        public PriceIntervalDiscount()
        {
            this.ProductGroups = new HashSet<ProductGroup>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExtendedBoolTableId { get; set; }
        public Nullable<System.Guid> ExtendedStringTableId { get; set; }
        public Nullable<System.Guid> ExtendedDecimalTableId { get; set; }
        public Nullable<System.Guid> ExtendedIntTableId { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable1Id { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable2Id { get; set; }
        public bool RunMonday { get; set; }
        public bool RunTuesday { get; set; }
        public bool RunWednesday { get; set; }
        public bool RunThursday { get; set; }
        public bool RunFriday { get; set; }
        public bool RunSaturday { get; set; }
        public bool RunSunday { get; set; }
        public System.DateTime MondayStartTime { get; set; }
        public System.DateTime MondayEndTime { get; set; }
        public System.DateTime TuesdayStartTime { get; set; }
        public System.DateTime TuesdayEndTime { get; set; }
        public System.DateTime WednesdayStartTime { get; set; }
        public System.DateTime WednesdayEndTime { get; set; }
        public System.DateTime ThursdayStartTime { get; set; }
        public System.DateTime ThursdayEndTime { get; set; }
        public System.DateTime FridayStartTime { get; set; }
        public System.DateTime FridayEndTime { get; set; }
        public System.DateTime SaturdayStartTime { get; set; }
        public System.DateTime SaturdayEndTime { get; set; }
        public System.DateTime SundayStartTime { get; set; }
        public System.DateTime SundayEndTime { get; set; }
        public decimal AmountOrPercent { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsPercentOff { get; set; }
        public bool IsDollarsOff { get; set; }
        public bool IsSpecifiedPrice { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
    }
}
