//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessorConfiguration
    {
        public ProcessorConfiguration()
        {
            this.Terminals = new HashSet<Terminal>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExtendedBoolTableId { get; set; }
        public Nullable<System.Guid> ExtendedStringTableId { get; set; }
        public Nullable<System.Guid> ExtendedDecimalTableId { get; set; }
        public Nullable<System.Guid> ExtendedIntTableId { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable1Id { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable2Id { get; set; }
        public string MerchantIdCredit { get; set; }
        public string MerchantPasswordCredit { get; set; }
        public string SecureDeviceIdCredit { get; set; }
        public string Ep1Credit { get; set; }
        public string Ep2Credit { get; set; }
        public string PortCredit { get; set; }
        public bool CreditIsEnabled { get; set; }
        public int ProcessingGatewayCredit { get; set; }
        public string MerchantIdGift { get; set; }
        public string MerchantPasswordGift { get; set; }
        public string SecureDeviceIdGift { get; set; }
        public string Ep1Gift { get; set; }
        public string Ep2Gift { get; set; }
        public string PortGift { get; set; }
        public bool GiftIsEnabled { get; set; }
        public int ProcessingGatewayGift { get; set; }
        public string MerchantIdRoomService { get; set; }
        public string MerchantPasswordRoomService { get; set; }
        public bool RoomServiceIsEnabled { get; set; }
        public int ProcessingGatewayRoom { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Terminal> Terminals { get; set; }
    }
}
