//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysConfig
    {
        public SysConfig()
        {
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
            this.VendorAccounts = new HashSet<VendorAccount>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExtendedBoolTableId { get; set; }
        public Nullable<System.Guid> ExtendedStringTableId { get; set; }
        public Nullable<System.Guid> ExtendedDecimalTableId { get; set; }
        public Nullable<System.Guid> ExtendedIntTableId { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable1Id { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable2Id { get; set; }
        public bool CanAcceptTips { get; set; }
        public string ReceiptLine1 { get; set; }
        public string ReceiptLine2 { get; set; }
        public string ReceiptLine3 { get; set; }
        public string ReceiptLine4 { get; set; }
        public bool ForceOrderOnScreenTimeout { get; set; }
        public int PrintQueueTimeout { get; set; }
        public System.Guid StoreId { get; set; }
        public string StoreCode { get; set; }
        public string TinNo { get; set; }
        public string TopReceiptMessage { get; set; }
        public string BottomReceiptMessage { get; set; }
        public string BusinessDayOfWeekStartDay { get; set; }
        public System.DateTime BusinessDayStartTime { get; set; }
        public bool PrintEmployeeCheckWithZeroSales { get; set; }
        public Nullable<System.Guid> CurrentBusinessDayId { get; set; }
        public int TableRecheckMinutes { get; set; }
        public bool AllowCardOnFile { get; set; }
        public int OrderTimeoutInMinutes { get; set; }
        public bool AllowDuplicateTables { get; set; }
        public decimal DailyHighWaterMark { get; set; }
        public bool EmailManagersAtHighWater { get; set; }
        public bool AutoCloseBusinessDay { get; set; }
        public bool RoundInclusiveTaxDown { get; set; }
        public bool RoundExclusiveTaxDown { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual ICollection<VendorAccount> VendorAccounts { get; set; }
    }
}
