//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorAccount
    {
        public VendorAccount()
        {
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.VendorProducts = new HashSet<VendorProduct>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExtendedBoolTableId { get; set; }
        public Nullable<System.Guid> ExtendedStringTableId { get; set; }
        public Nullable<System.Guid> ExtendedDecimalTableId { get; set; }
        public Nullable<System.Guid> ExtendedIntTableId { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable1Id { get; set; }
        public Nullable<System.Guid> ExtendedLinkTable2Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Telephone { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string BranchName { get; set; }
        public string BankName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Active { get; set; }
        public string EmailAddress { get; set; }
        public decimal AccountLimit { get; set; }
        public string AccountTerms { get; set; }
        public bool HasNoHighLimit { get; set; }
        public string Fax { get; set; }
        public string Country { get; set; }
        public string VendorType { get; set; }
        public string Notes { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] TimeStamp { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid StoreId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> SysConfig_Id { get; set; }
    
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual SysConfig SysConfig { get; set; }
        public virtual ICollection<VendorProduct> VendorProducts { get; set; }
    }
}
