//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePos.Persistance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using OnePos.Domain;
    using System.Data;
    using System.Collections.Generic;

    public delegate void OnDisposedDelegate( object sender, EventArgs args );
    
    public interface IOnePosEntities : IDisposable
    {
    
    
    	
        int? CommandTimeout { get; set; }
    
    	event OnDisposedDelegate OnDisposed;
        long CreateStore(Store store);
        bool UpdateStore(Store store);
        DataTable GetOnePosStoreTypes();
        DataTable GetOnePosStores();
        DataTable GetOnePosStoreDatabases();
        bool UpdateOnePosStoreStatus(long StoreId, int StatusId);
        bool UpdateOnePosStoreDatabaseConnections(long StoreId, int MainDBConnectionId, int BackupDBConnectinId);
        bool CreateVerticalDatabaseConnections(string Address, string DatabaseName, string UserName, string Password, int StoreTypeId, int IsMainDB);
        long CreateStoreAccessModules(StoreAccessModules storeaccessmodules); 
        DataTable GetStoreAccessModules(long storeId);

        void BulkQuerySample(List<string> QueriesList);
        int SaveChanges(); 
    	  
    	OnePosEntities CreateEntitiesForSpecificDatabaseName(string dataSource, string databaseName, bool contextOwnsConnection = true);
    
        IDbSet<AccessLevel> AccessLevels { get; set; }
        IDbSet<AutoGratuity> AutoGratuities { get; set; }
        IDbSet<AutoGratuityClone> AutoGratuityClones { get; set; }
        IDbSet<Break> Breaks { get; set; }
        IDbSet<BusinessDay> BusinessDays { get; set; }
        IDbSet<CustomerOrder> CustomerOrders { get; set; }
        IDbSet<Customer> Customers { get; set; }
        IDbSet<DayPart> DayParts { get; set; }
        IDbSet<Deposit> Deposits { get; set; }
        IDbSet<DiscountClone> DiscountClones { get; set; }
        IDbSet<Discount> Discounts { get; set; }
        IDbSet<ExceptionModifierGroup> ExceptionModifierGroups { get; set; }
        IDbSet<ExceptionModifier> ExceptionModifiers { get; set; }
        IDbSet<ExtendedBoolTable> ExtendedBoolTables { get; set; }
        IDbSet<ExtendedDecimalTable> ExtendedDecimalTables { get; set; }
        IDbSet<ExtendedIntTable> ExtendedIntTables { get; set; }
        IDbSet<ExtendedLinkTable> ExtendedLinkTables { get; set; }
        IDbSet<ExtendedStringTable> ExtendedStringTables { get; set; }
        IDbSet<FingerPassword> FingerPasswords { get; set; }
        IDbSet<ForcedModifierGroup> ForcedModifierGroups { get; set; }
        IDbSet<ForcedModifier> ForcedModifiers { get; set; }
        IDbSet<GiftCardsSold> GiftCardsSolds { get; set; }
        IDbSet<GlCode> GlCodes { get; set; }
        IDbSet<HouseAccount> HouseAccounts { get; set; }
        IDbSet<InclusiveTipRate> InclusiveTipRates { get; set; }
        IDbSet<InventoryCountLog> InventoryCountLogs { get; set; }
        IDbSet<InvoiceLineItem> InvoiceLineItems { get; set; }
        IDbSet<JobCode> JobCodes { get; set; }
        IDbSet<LayoutObj> LayoutObjs { get; set; }
        IDbSet<LocationLayout> LocationLayouts { get; set; }
        IDbSet<MenuGroup> MenuGroups { get; set; }
        IDbSet<Menu> Menus { get; set; }
        IDbSet<NoSale> NoSales { get; set; }
        IDbSet<OrderedRecipe> OrderedRecipes { get; set; }
        IDbSet<Order> Orders { get; set; }
        IDbSet<PageLayoutStructure> PageLayoutStructures { get; set; }
        IDbSet<PayGrade> PayGrades { get; set; }
        IDbSet<PaymentReason> PaymentReasons { get; set; }
        IDbSet<Payment> Payments { get; set; }
        IDbSet<PayrollRun> PayrollRuns { get; set; }
        IDbSet<PciLog> PciLogs { get; set; }
        IDbSet<PriceIntervalDiscount> PriceIntervalDiscounts { get; set; }
        IDbSet<PrinterExclusion> PrinterExclusions { get; set; }
        IDbSet<PrinterGroup> PrinterGroups { get; set; }
        IDbSet<Printer> Printers { get; set; }
        IDbSet<ProcessorConfiguration> ProcessorConfigurations { get; set; }
        IDbSet<ProductGroup> ProductGroups { get; set; }
        IDbSet<Product> Products { get; set; }
        IDbSet<ProfitCenter> ProfitCenters { get; set; }
        IDbSet<PurchaseChildOrder> PurchaseChildOrders { get; set; }
        IDbSet<PurchaseOrder> PurchaseOrders { get; set; }
        IDbSet<RecipeIngredient> RecipeIngredients { get; set; }
        IDbSet<RecipeProduct> RecipeProducts { get; set; }
        IDbSet<Recipe> Recipes { get; set; }
        IDbSet<RevenueType> RevenueTypes { get; set; }
        IDbSet<Role> Roles { get; set; }
        IDbSet<Sale> Sales { get; set; }
        IDbSet<Schedule> Schedules { get; set; }
        IDbSet<Shift> Shifts { get; set; }
        IDbSet<SMSConfiguration> SMSConfigurations { get; set; }
        IDbSet<SpecialPay> SpecialPays { get; set; }
        IDbSet<StoreLocation> StoreLocations { get; set; }
        IDbSet<SurchargeConfigurationClone> SurchargeConfigurationClones { get; set; }
        IDbSet<SurchargeConfiguration> SurchargeConfigurations { get; set; }
        IDbSet<SurchargeGroup> SurchargeGroups { get; set; }
        IDbSet<SysConfig> SysConfigs { get; set; }
        IDbSet<TaxConfigurationClone> TaxConfigurationClones { get; set; }
        IDbSet<TaxConfiguration> TaxConfigurations { get; set; }
        IDbSet<TaxGroup> TaxGroups { get; set; }
        IDbSet<TenderType> TenderTypes { get; set; }
        IDbSet<TerminalPrinterMap> TerminalPrinterMaps { get; set; }
        IDbSet<Terminal> Terminals { get; set; }
        IDbSet<TimePunch> TimePunches { get; set; }
        IDbSet<Transaction> Transactions { get; set; }
        IDbSet<User> Users { get; set; }
        IDbSet<VendorAccount> VendorAccounts { get; set; }
        IDbSet<VendorProduct> VendorProducts { get; set; }
        IDbSet<WorkCenter> WorkCenters { get; set; }
    }
}
